title   = "Proxy"
keep    = 60
timeout = 10


#以下两个实例分别表示http和socket5
#service后面的http和socket5可以随意修改，只要不重复

[service.http]
addr  = "绑定到本地机器的端口，如 :60053"
# 是否通过ssh连接
overssh = false
# 是否根据pac来自动判断是否通过ssh连接
overpac = false
# 是否http代理，false表示用socket5
ishttp = true

[service.socket5]
addr  = "绑定到本地机器的端口，如 :60053"
overssh = false
overpac = false
ishttp = false
[ssh]
addr  = "ssh服务器的ip，如 192.168.1.53:22"
user  = "跳板机的用户帐号"
auth  = "认证信息，可以是密码、密钥文件、密钥文本"
phrase= "生成ssh密钥时输入的passphrase，如果没有请留空"
#超时时间，单位秒
timeout = 10
enable = true
