title   = "Proxy"
keep    = 60
timeout = 10

[http]
addr  = "绑定到本地机器的端口，如 :60053"
overssh = false
[http_ssh]
addr  = "绑定到本地机器的端口，如 :60053"
overssh = true
[socket5]
addr  = "绑定到本地机器的端口，如 :60053"
overssh = false
[socket5_ssh]
addr  = "绑定到本地机器的端口，如 :60053"
overssh = true
[ssh]
addr  = "ssh服务器的ip，如 192.168.1.53:22"
user  = "跳板机的用户帐号"
auth  = "认证信息，可以是密码、密钥文件、密钥文本"
enable = true
